### ISSUE TITLE
정적 페이지 수정중

### ISSUE THREAD

**Issue by mlee528** [19-1-skku-oss/2019-1-OSS-L1#13]
저희 정적페이지 디자인 싹 바꾸는 중인데,
혹시 테마 적용 후에 한글입력 가능하게 하는법 아시는분 계실까요??
지금 무조건 다 영어로만 입력가능하게 되어서, 포스트에 한글이 입력되면 에러가 나더라구요!ㅜ

*민종쓰 help wanted 어떻게 하신건가요...ㅎ

**Comment by mjyoo2** [comment]
label은 달아드렸습니다.
어떤 테마를 사용중이신지 알려주셔야 확인 가능할 것 같습니다.

**Comment by mjyoo2** [comment]
테마를 fork 한 original repo에 가서 이슈로 물어보시는게 나을 것 같습니다.
지금 저희 static page에 사용하는 테마는 기본적으로 한글을 지원한다는 것을 확인하고 가져온 것이라서.. 직접 물어보는게 맞는것 같습니다.

**Comment by Joeycho** [comment]
@martinalee94 

https://github.com/19-1-skku-oss/2019-1-OSS-L1/blob/master/docs/_layouts/page.html

코드 위에 보면, 

```
---
layout: compress
---
<html lang="{{ page.lang | default: site.lang | default: "en_US" }}">
```

이런 부분이 있어요. html setting에서 language 부분을 바꾸면 페이지에서 한글을 지원할꺼에요.

저도 한번 해볼께요.

**Comment by Joeycho** [comment]
@martinalee94 

```
---
layout: compress
---
<html lang="{{ page.lang | default: site.lang | default: "ko" }}">
```
수정완료한 거 같은데, 확인부탁해요.
