### ISSUE TITLE
한국어 번역 작업 포스트 업데이트!

### ISSUE THREAD

**Issue by mlee528** [19-1-skku-oss/2019-1-OSS-L1#29]
어제 민종이가 gh-pages 브랜치에 한국어 번역된 작업물들 올리면
어디론가 머지해서 최종적으로 페이지에서 볼 수 있는거라고 했었는데
이걸 제가 스스로 해보고 싶어서요!
어떻게 하는지 알려주실수 있나요~>

**Comment by Joeycho** [comment]
이제는 할 수 있죠? 혹시 아직 헤깔리는 부분이라도??

**Comment by mlee528** [comment]
이젠 완벽하게 마스터했스무니닷
