### ISSUE TITLE
프로젝트 소개 포스팅

### ISSUE THREAD

**Issue by mlee528** [19-1-skku-oss/2019-1-OSS-L1#30]
저희 오소실 실습 프로젝트에 대한 포스트 하나를 써야할 거 같은데
어떤 내용 넣으면 좋을지 같이 얘기해봐요!

**Comment by mlee528** [comment]
issues랑 projects 화면 캡쳐해서 우리가 이런것들했다 소개하는거 넣으려구용일단!

**Comment by Joeycho** [comment]
좋아요~! 그거랑 가능하면 pytest test한 거 캡쳐한 것도 같이 소개하는데에 넣어요!

**Comment by Joeycho** [comment]
아, Pull requests리스트랑, 그리고 꼭 뺴먹지 말고 언급할 것은

Projects에서도 우리 팀 계획 관리했던 부분들이요~!
