### ISSUE TITLE
wiki 페이지 수정중

### ISSUE THREAD

**Issue by mlee528** [19-1-skku-oss/2019-1-OSS-L1#31]
위키 페이지 수정중입니다~ 
옆에 사이드바 추가해서 목록 정리할 예정이니 참고해주시구
한 번씩 보시면서 각자 더 넣고싶은건 넣어봐요!

**Comment by Joeycho** [comment]
그냥 위키에만 두기에는 아까운데~! 그래도 위키의 특별함으로 남겨둘까요?

**Comment by mlee528** [comment]
ㅎㅎㅎ wiki에도 넣어놓고 페이지에도 넣고~ 포스트에도 넣고~ 다 넣죠뭐ㅎㅎㅎ
