### ISSUE TITLE
발표 흐름 정리

### ISSUE THREAD

**Issue by mlee528** [19-1-skku-oss/2019-1-OSS-L1#33]
오늘 드디어 발표날!!!
흐름 좀 잡고 어떤 내용 발표할지 같이 얘기해봅시당!

**Comment by mlee528** [comment]
첫번째는 pytest 간략한 소개
마지막은 느낀점 짤막하게

**Comment by mjyoo2** [comment]
pytest 소개-> milestone -> static page 소개-> 느낀점
