### ISSUE TITLE
input 관련 함수에 주석을 달아주세요.

### ISSUE THREAD

**Issue by mjyoo2** [19-1-skku-oss/2019-1-OSS-L1#6]
전체적으로 코드에 주석이 부족합니다.
input에 관련된 함수를 천천히 살펴보고 있는데 함수에는 정확한 주석이  없어서 해석이 힘듭니다.
전체 함수에 주석을 다는것은 힘들더라도 input 관련된 함수에는 주석을 달아야 할 것 같습니다.

**Comment by Joeycho** [comment]
네, 알겠습니다!

**Comment by mlee528** [comment]
네~:) 알겠습니당!!!

**Comment by hyungjc99** [comment]
넵. 알겠습니다!

**Comment by Joeycho** [comment]
@mjyoo2 살펴보고 있는 input 관련된 함수 reference link로 걸어줄 수 있나요??
